name: calamitech
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  go_router: ^14.6.0
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  hexcolor: ^3.0.1
  location: ^8.0.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  meta: ^1.16.0
  url_launcher: ^6.3.1
  pusher_channels_flutter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/calamitech.png
    - assets/images/home.png
    - assets/images/fire.png
    - assets/images/safety.png
    - assets/images/more.png
    - assets/images/heartshield.png
    - assets/images/gas.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
